import jabalOmarfavIco from "../../public/jabalomarLogo.ico";
import smascofavIco from "../../public/samscoLogo.png";
export const companies = {
  jabalomar: {
    name: "jabalomar",
    username: "JABAL-OMAR-IR",
    password: "JWQ0YTNj1YTllOMjI0M2JhNm7Y5ND7x9urTg3NW/RlO4TcyY2JlMGE==",
    styles: {
      "--main-color": "#374c5f",
      "--bg-light": "#9da07c",
      "--link-color": "#374c5f",
    },
    metaTags: {
      titleEn: "jabal omar || Investor Relations",
      titleAr: "جبل عمر || علاقات المستثمرين",
      favIco:jabalOmarfavIco
    },
  },
  smasco: {
    name: "smasco",
    username: "SMASCO-IR",
    password: "SMQ0YTNj1YTllOMjI0M2JhNm7Y5ND7x9urTg3NW/RlO4TcyY2JlMGE==",
    styles: {
      "--main-color": "#00a164",
      "--light-main-color": "#00a164",
      "--link-color": "#4b4b4b",
      "--border-color": "#dee2e6",
    },
    metaTags: {
      titleEn: "smasco || Investor Relations",
      titleAr: " سماسكو || علاقات المستثمرين",
      favIco:smascofavIco
    },
  },
  tamkeen: {
    name: "tamkeen",
    username: "Tamkeen_IR",
    password: "TKNS21-IK67655584HHK78SG8967C8F-AF007F-55",
    styles: {
      "--main-color": "#084d86",
      "--link-color": "#4b4b4b",
    },
    metaTags: {
      titleEn: "Tamkeen || Investor Relations",
      titleAr: " تمكين || علاقات المستثمرين",
      favIco:smascofavIco
    },
  },
};
